In [3]:
import numpy as np

In [4]:
revenue = np.array([[180, 200, 220], [24, 30, 36], [12, 18, 30]])
expense = np.array([[80, 90, 100], [10, 16, 20], [8, 10, 10]])

In [5]:
profit = revenue - expense

In [6]:
profit

array([[100, 110, 120],
       [ 14,  14,  16],
       [  4,   8,  20]])

In [7]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [8]:
price_per_unit*units #iki salah, namanya broadcast klo di numpy

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [9]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])