In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement']

In [3]:
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
one_hot("amazing restaurant", 30)

[8, 14]

In [7]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[26, 21],
 [8, 14],
 [17, 22],
 [26, 2, 12],
 [1, 24, 4],
 [8, 21],
 [11, 24, 7],
 [3, 17],
 [3, 16],
 [18, 14]]

In [8]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[26, 21,  0],
       [ 8, 14,  0],
       [17, 22,  0],
       [26,  2, 12],
       [ 1, 24,  4],
       [ 8, 21,  0],
       [11, 24,  7],
       [ 3, 17,  0],
       [ 3, 16,  0],
       [18, 14,  0]])

In [9]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name="embeding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [10]:
X = padded_reviews
y = sentiment

In [11]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embeding (Embedding)        (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
loss, accuracy = model.evaluate(X, y)



1/1 [==============================] - 1s 1s/step - loss: 0.6875 - accuracy: 0.6000


In [14]:
weights = model.get_layer('embeding').get_weights()[0]
len(weights)

30

In [16]:
weights[11]

array([ 0.01759461, -0.0291055 ,  0.00261767,  0.03736533, -0.0034182 ],
      dtype=float32)

In [17]:
weights[3]

array([ 0.02598676,  0.04512805, -0.0120017 ,  0.01753068, -0.0062083 ],
      dtype=float32)